=== webcomponents-preview/client/pr/41/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "additionalReadmeGroupName": {
            "type": "string"
        },
        "additionalReadmes": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "type": "array"
        },
        "excludeElements": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "fallbackGroupName": {
            "type": "string"
        },
        "initialActiveElement": {
            "type": "string"
        },
        "initialPreviewTab": {
            "enum": [
                "examples",
                "readme",
                "viewer"
            ],
            "type": "string"
        },
        "title": {
            "type": "string"
        }
    },
    "type": "object"
}

=== webcomponents-preview/client/latest/config.json
{
  "$schema": "./config.schema.json",
  "excludeElements": ["wcp-root"],
  "initialActiveElement": "wcp-button",
  "initialPreviewTab": "viewer",
  "additionalReadmeGroupName": "Readme",
  "additionalReadmes": [
    {
      "name": "Web Component Preview",
      "url": "README.md"
    },
    {
      "name": "Test markdown",
      "url": "assets/markdown.md"
    },
    {
      "name": "Test inline links",
      "url": "assets/inline-links.md"
    },
    {
      "name": "Test code",
      "url": "assets/code.md"
    }
  ]
}
